name: Create a pull request for release.

on:
  push:
    branches: main

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Fetch all branches
        run: git fetch origin

      - name: Create release pr
        run: |
          COMMITS=$(git log origin/release..origin/main --pretty=format:"- %s (%h) by %an")

          gh pr create \
            -B 'release' \
            -t 'release' \
            -b "## 変更内容\n\n$COMMITS" \
            -d