name: Create a pull request for release.

on:
  push:
    branches: main

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - name: Create release pr
        run: |
          gh pr create -B 'release' -t 'release' -b ""