name: Create Release PR

on:
  push:
    branches:
      - main

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release PR
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Release to production"
          body: "This PR merges main branch changes into release branch"
          head: "main"
          base: "release"